backend/favit/urls.py
from django.urls import path

from favit import views

app_name = "favit"

urlpatterns = [
    path("add-or-remove", views.add_or_remove, name="add_or_remove"),
    path("remove", views.remove, name="remove"),
]

backend/references/urls.py
from django.urls import path, re_path

from .views import (
    AuthorDetailView,
    ReferenceAutocomplete,
    ReferenceDetailView,
    add_excerpt,
)

app_name = "references"

urlpatterns = [
    path(
        "autocomplete/",
        ReferenceAutocomplete.as_view(create_field="doi"),
        name="reference-autocomplete",
    ),
    re_path(r"^author/(?P<pk>[-\w]+)/$", AuthorDetailView.as_view(), name="author-detail"),
    re_path(r"^ajax/add_excerpt/(?P<pk>[-\w]+)$", add_excerpt, name="add_excerpt"),
    re_path(r"^(?P<pk>[-\w\/\.]+)/$", ReferenceDetailView.as_view(), name="reference-detail"),
]

backend/references/models.py
from datetime import datetime

import pytz
from django.contrib.auth import get_user_model
from django.core.exceptions import ObjectDoesNotExist
from django.core.validators import (
    MaxLengthValidator,
    MaxValueValidator,
    MinLengthValidator,
    MinValueValidator,
)
from django.db import models
from django.urls import reverse
from model_utils.models import TimeStampedModel

from proteins.validators import validate_doi

from .helpers import doi_lookup, name_to_initials

User = get_user_model()


class Author(TimeStampedModel):
    family = models.CharField(max_length=80)
    given = models.CharField(max_length=80)
    initials = models.CharField(max_length=10)
    publications = models.ManyToManyField("Reference", through="ReferenceAuthor")

    @property
    def protein_contributions(self):
        return {p for ref in self.publications.all() for p in ref.primary_proteins.all()}

    @property
    def first_authorships(self):
        return [p.reference for p in self.referenceauthor_set.filter(author_idx=0)]

    @property
    def last_authorships(self):
        return [p.reference for p in self.referenceauthor_set.all() if p.author_idx == p.author_count - 1]

    def save(self, *args, **kwargs):
        self.initials = name_to_initials(self.initials)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("references:author-detail", args=[self.id])

    def full_name(self):
        if self.given:
            return f"{self.given} {self.family}".title()
        else:
            return f"{self.initials} {self.family}".title()

    def __repr__(self):
        return f"Author(family='{self.family}', given='{self.given}'')"

    def __str__(self):
        return f"{self.family} {self.initials}"

    class Meta:
        unique_together = (("family", "initials"),)

    def to_dict(self):
        return {
            "family": self.family,
            "given": self.given,
            "initials": self.initials,
        }

class Reference(TimeStampedModel):
    doi = models.CharField(
        max_length=50,
        unique=True,
        blank=False,
        verbose_name="DOI",
        validators=[validate_doi]
    )
    pmid = models.CharField(max_length=15, unique=True, null=True, blank=True, verbose_name="Pubmed ID")
    title = models.CharField(max_length=512, blank=True)
    journal = models.CharField(max_length=512, blank=True)
    pages = models.CharField(max_length=20, blank=True)
    volume = models.CharField(max_length=10, blank=True, default="")
    issue = models.CharField(max_length=10, blank=True, default="")
    firstauthor = models.CharField(max_length=100, blank=True, default="")
    citation = models.CharField(max_length=256, blank=True, default="")
    date = models.DateField(null=True, blank=True)
    year = models.PositiveIntegerField(
        validators=[
            MinLengthValidator(4),
            MaxLengthValidator(4),
            MinValueValidator(1960),
            MaxValueValidator(datetime.now(pytz.utc).year + 1),
        ],
        help_text="YYYY",
    )
    authors = models.ManyToManyField("Author", through="ReferenceAuthor")
    summary = models.CharField(max_length=512, blank=True, help_text="Brief summary of findings")

    created_by = models.ForeignKey(
        User,
        related_name="reference_author",
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )
    updated_by = models.ForeignKey(
        User,
        related_name="reference_modifier",
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )

    class Meta:
        ordering = ("date",)

    def get_authors(self):
        return self.authors.order_by("referenceauthor")

    @property
    def first_author(self):
        try:
            return self.get_authors()[0]
        except Exception:
            return None

    @property
    def protein_secondary_reference(self):
        from proteins.models import ProteinTF
        return ProteinTF.objects.exclude(id__in=self.primary_proteins.values_list("id", flat=True))

    def get_citation(self, authorlist):
        try:
            if len(authorlist) == 0:
                if self.title:
                    return f"{self.title[:30]}..."
                else:
                    return f"{self.doi}"
            elif len(authorlist) > 2:
                middle = " et al. "
            elif len(authorlist) == 2:
                secondauthor = authorlist[1].family
                middle = f" & {secondauthor} "
            else:
                middle = " "
            self.firstauthor = authorlist[0].family
            return f"{self.firstauthor}{middle}({self.year})"
        except ObjectDoesNotExist:
            return f"doi: {self.doi}"

    def get_absolute_url(self):
        return reverse("references:reference-detail", args=[self.id])

    def __repr__(self):
        return f"Reference(doi={self.doi})"

    def __str__(self):
        try:
            return self.citation
        except Exception:
            return super().__str__()

    def clean(self):
        if self.doi:
            self.doi = self.doi.strip()

    def save(self, skipdoi=False, *args, **kwargs):
        if self.doi:
            self.doi = self.doi.lower()
        if not skipdoi:
            info = doi_lookup(self.doi)
            authors = info.pop("authors")
            authorlist = []
            for author in authors:
                auth, _ = Author.objects.get_or_create(
                    initials=name_to_initials(author["given"]),
                    family=author["family"],
                    defaults={"given": author["given"].replace(".", "")},
                )
                authorlist.append(auth)
            for k, v in info.items():
                setattr(self, k, v)
            self.citation = self.get_citation(authorlist)
        super().save(*args, **kwargs)
        if not skipdoi:
            ReferenceAuthor.objects.filter(reference_id=self.id).delete()
            for idx, author in enumerate(authorlist):
                authmemb = ReferenceAuthor(reference=self, author=author, author_idx=idx)
                authmemb.save()

    def prot_secondary(self):
        return [p.gene for p in self.protein_secondary_reference]

    def prot_primary(self):
        return [p.gene for p in self.primary_proteins.all()]

    def _excerpts(self):
        return [exc.content for exc in self.excerpts.all()]

    def get_date(self):
        return self.date.isoformat()

    def url(self):
        return self.get_absolute_url()

    def to_dict(self):
        data = {
            "doi": self.doi,
            "journal": self.journal,
            "pmid": self.pmid,
            "year": self.year,
            "first_author": self.first_author,
            "title": self.title,
            "citation": self.citation,
            "date": self.date.isoformat() if self.date else None,
            "prot_primary": self.prot_primary(),
            "prot_secondary": self.prot_secondary(),
            "_excerpts": self._excerpts(),
            "url": self.url(),
        }
        # for k, v in data.items():
        #     print(f"{k}: {v} ({type(v)})")
        return data

class ReferenceAuthor(models.Model):
    reference = models.ForeignKey(Reference, on_delete=models.CASCADE)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    author_idx = models.PositiveSmallIntegerField()

    class Meta:
        ordering = ["author_idx"]

    def __str__(self):
        return f"<AuthorMembership: {self.author} in doi: {self.reference.doi}>"

    @property
    def author_count(self):
        return self.reference.authors.count()

backend/references/forms.py
from django import forms
from django.contrib.auth.models import User

from references.models import Author, Reference


class UserMixin:
    def clean_user(self):
        if not self.cleaned_data["added_by"]:
            return User()
        return self.cleaned_data["added_by"]

    def clean_updated_by(self):
        if not self.cleaned_data["updated_by"]:
            return User()
        return self.cleaned_data["updated_by"]


class AuthorForm(UserMixin, forms.ModelForm):
    class Meta:
        model = Author
        fields = ["family", "given"]


class ReferenceForm(UserMixin, forms.ModelForm):
    refetch_info_on_save = forms.BooleanField(required=False)

    class Meta:
        model = Reference
        fields = ["pmid", "doi", "title", "refetch_info_on_save"]

backend/references/views.py
import reversion
from dal import autocomplete
from django.core.mail import mail_managers
from django.http import Http404, HttpResponseNotAllowed, JsonResponse
from django.utils.html import strip_tags
from django.views.generic import DetailView, ListView

from repeatome.util import is_ajax
from proteins.models import Excerpt
from proteins.util.helpers import link_excerpts

from .models import Author, Reference


class AuthorDetailView(DetailView):
    """renders html for single author page"""

    queryset = Author.objects.all().prefetch_related(
        "publications", "publications__authors", "publications__primary_proteins"
    )


class ReferenceListView(ListView):
    """renders html for single reference page"""

    queryset = Reference.objects.all().prefetch_related("authors", "primary_proteins")


class ReferenceDetailView(DetailView):
    """renders html for single reference page"""

    queryset = Reference.objects.all().prefetch_related("authors")

    def get_object(self, queryset=None):
        try:
            return super().get_object(queryset=queryset)
        except (ValueError, Http404):
            # allow for doi to be used in url as well
            if queryset is None:
                queryset = self.get_queryset()
            try:
                doi = self.kwargs.get(self.pk_url_kwarg)
                queryset = queryset.filter(doi=doi.lower())
                obj = queryset.get()
            except queryset.model.DoesNotExist as e:
                raise Http404("No reference found matching this query") from e
            return obj

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["excerpts"] = link_excerpts(self.object.excerpts.all())
        return data


class ReferenceAutocomplete(autocomplete.Select2QuerySetView):
    def get_results(self, context):
        """Return data for the 'results' key of the response."""
        return [
            {
                "id": result.doi,
                # 'slug': result.slug,
                "text": result.citation,
            }
            for result in context["object_list"]
        ]

    def get_queryset(self):
        # Don't forget to filter out results depending on the visitor !
        if not self.request.user.is_authenticated:
            return Reference.objects.none()
        qs = Reference.objects.all()
        if self.q:
            qs = qs.filter(doi__icontains=self.q)
        return qs


def add_excerpt(request, pk=None):
    if not is_ajax(request):
        return HttpResponseNotAllowed([])
    try:
        with reversion.create_revision():
            ref = Reference.objects.get(pk=pk)
            content = request.POST.get("excerpt_content")
            if content:
                # P.references.add(ref)
                Excerpt.objects.create(reference=ref, content=strip_tags(content), created_by=request.user)
                if not request.user.is_staff:
                    msg = (
                        f"User: {request.user.username}\nReference: {ref}, {ref.title}"
                        f"\nExcerpt: {strip_tags(content)}\n{request.build_absolute_uri(ref.get_absolute_url())}"
                    )
                    mail_managers("Excerpt Added", msg, fail_silently=True)
                reversion.set_user(request.user)
                reversion.set_comment(f"Excerpt from {ref} added")
        return JsonResponse({"status": "success"})
    except Exception as e:
        return JsonResponse({"status": "failed", "msg": e})

backend/references/templates/references/author_detail.html
{% extends "base.html" %}


{% block title %}{{ author.full_name }} :: Fluorescent Protein Database {% endblock %}
{% block meta-description %}References and fluorescent proteins attributed to {{ author.full_name }} at FPbase: the Fluorescent Protein Database.  Including: {% for ref in author.publications.all %}{% for protein in ref.primary_proteins.all %}{{ protein.name }}{% if not forloop.last %}, {% endif %}{% endfor %}{% if not forloop.last %}, {% endif %}{% endfor %}.{% endblock %}


{% block content %}

    <div class="alert alert-dismissible alert-info small">
      Please note: due to the ambiguity of author names, it is extremely hard to be confident about authorships.  There may be errors in the names or attributions of these author pages.  Please check the actual publication pages for more accurate information.
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
	<div class="author-detail">
		<h1>{{ author.full_name }}</h1>

    <ol class="pl-4">
      {% for ref in author.publications.all %}

        <li class="mt-2">
          {% include "_reference.html" %}

          <ol class='protein-list'>
            <h5>Primary Proteins: </h5>
            {% for protein in ref.primary_proteins.all %}
              <li><a href="{{ protein.get_absolute_url }}">{{ protein.name }}</a></li>
            {% endfor %}
          </ol>

          {% if ref.protein_secondary_reference.exists %}
              <ol class='protein-list'>
                <h5>Additional Proteins:</h5>
                {% for protein in ref.protein_secondary_reference.all %}
                  <li><a href="{{ protein.get_absolute_url }}">{{ protein.name }}</a></li>
                {% endfor %}
              </ol>
          {% endif %}
        </li>
      {% endfor %}
    </ol>

	</div>

{% endblock content %}


{% block extrafooter %}
    {% if request.user.is_staff %}
      {% load admin_urls %}
      <a href="{% url 'admin:references_author_change' author.id %}">{{ author}} on admin</a><br>
    {% endif %}
{% endblock extrafooter %}

backend/references/templates/references/reference_detail.html
{% extends "base.html" %}
{% load flag_object from protein_tags %}

{% block title %}{{ reference.citation  }} :: Fluorescent Protein Database {% endblock %}
{% block meta-description %}Fluorescent proteins introduced or referenced by {{ reference.citation  }}: {{reference.title}}.  Including: {% for protein in reference.primary_proteins.all %}{{ protein.name }}{% if not forloop.last %}, {% endif %}{% endfor %}{% endblock %}

{% block content %}

	<div class="primary-ref references">
		{% include "_reference.html" with ref=reference %}
	</div>

  {% if  reference.primary_proteins.count %}
	<ol class='protein-list'>
		<h5>Primary Proteins: </h5>
		{% for protein in reference.primary_proteins.all %}
			<li><a href="{{ protein.get_absolute_url }}">{{ protein.gene_family.gene_family }}</a></li>
		{% endfor %}
	</ol>
  {% endif %}

	{% if reference.protein_secondary_reference.count > 0 %}
	    <ol class='protein-list'>
	    	<h5>Secondary Proteins:</h5>
	    	{% for protein in reference.protein_secondary_reference.all %}
	    		<li class='mr-1'><a href="{{ protein.get_absolute_url }}">{{ protein.gene }}{% if not forloop.last %},{% endif %}</a></li>
	    	{% endfor %}
	    </ol>
	{% endif %}


{% comment %} {% if reference.bleach_measurements.count %}

<h4 class='mt-4'>Bleach Measurements</h4>
  <table class="table table-striped mt-4 flip-scroll">
    <thead>
      <tr class="table-header">
        <th>Protein (state)</th>
        <th>t<sub>1/2</sub> (s)</th>
        <th>Power</th>
        <th>Light</th>
        <th>Mode</th>
        <th>In Cell</th>
        <th>Fusion</th>
        <th>˚C</th>

      </tr>
    </thead>
    <tbody>
        {% for measurement in reference.bleach_measurements.all  %}
          <tr class="data">
            <td><a href="{{measurement.state.protein.get_absolute_url}}">{{measurement.state}}</a></td>
            <td>{{measurement.rate}}</td>
            <td>
            {% if measurement.power > 0 %}{{measurement.power}}{% if measurement.units %} <span class='small'>{{measurement.units}}</span>{% endif %}{% elif measurement.power < 0 %}<span class='text-muted'>NR</span>{% endif %}
            </td>
            <td>{{measurement.get_light_display}}</td>
            <td>{{measurement.get_modality_display}}</td>
            <td class='text-muted small'>{% if measurement.in_cell == 0 %}
              <i class="fas fa-times">
            {% elif measurement.in_cell == 1 %}
              <i class="fas fa-check">
            {% else %}
            {% endif %}</td>
            <td>{{measurement.fusion}}</td>
            <td>{{measurement.temp | default:''}}</td>
          </tr>
        {% endfor %}
    </tbody>
  </table>

  <div class="align-self-end mt-0 mb-2 clearfix">
    <a href="{% url 'bleaching' %}" class='float-left small text-muted mt-1 mb-2 ml-2'>A caution on interpretation of photostability measurements</small></a>
    <a href="{% url 'proteins:bleach-comparison' pk=reference.pk %}" class='text-info'>
      <div class="">
          <small class="d-none d-sm-inline float-right mt-1">Add photostability measurements</small>
          <button type="button" class="btn btn-info btn-block mt-3 mb-3 d-block d-sm-none"><i class="fas fa-clock mr-2"></i>Add photostability measurements</button>
      </div>
    </a>
  </div>
{% else %}
      <a href="{% url 'proteins:bleach-comparison' pk=reference.pk %}" class='text-info'>
        <div class="mt-4">
            <small class="d-none d-sm-inline mt-1">Add photostability measurements</small>
            <button type="button" class="btn btn-info btn-block mt-3 mb-3 d-block d-sm-none"><i class="fas fa-clock mr-2"></i>Add photostability measurements</button>
        </div>
      </a>
{% endif %}
 {% endcomment %}



{% comment %} 
{% if reference.oser_measurements.count %}
<div class="attributes mt-4">
  <h4>OSER Measurements</h4>
    <table class="table table-striped flip-scroll">
      <thead>
        <tr class="table-header">
          <th>Protein</th>
          <th>&percnt; Normal Cells</th>
          <th>OSER/NE ratio</th>
          <th>Cell Type</th>
          <th>Temp (˚C)</th>
        </tr>
      </thead>
      <tbody>
        {% for oserm in reference.oser_measurements.all  %}
          <tr>
            <td><a href="{{oserm.protein.get_absolute_url}}">{{oserm.protein}}</a></td>
            <td>{{oserm.percent|default:'-'}} {% if oserm.percent_stddev %} ± {{oserm.percent_stddev}}{% endif %}
            {% if oserm.percent_ncells %} <span class='small text-muted'>({{oserm.percent_ncells}} cells)</span>{% endif %}</td>
            <td>{{oserm.oserne|default:'-'}} {% if oserm.oserne_stddev %} ± {{oserm.oserne_stddev}}{% endif %}
            {% if oserm.oserne_ncells %} <span class='small text-muted'>({{oserm.oserne_ncells}} cells)</span>{% endif %}</td>
            <td>{{oserm.celltype|default:'-'}}</td>
            <td>{{oserm.temp|default:'-'}}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endif %} {% endcomment %}


<div class="excerpts mt-3">
  <h3>Excerpts <a tabindex="0" data-toggle="popover" data-trigger="focus" title="Excerpts" data-placement="right" data-content="Excerpts are snippets from publications that capture <strong>key</strong> information about a protein that does not easily fit into one of the existing fields (such as a summary, motivation, or observation).<hr>If you believe an excerpt is inappropriate or taken out of context, you may flag it for review if you are logged in."><i class="fas fa-info-circle ml-2 text-muted" style='font-size: 1rem; position: relative; top: -1px; cursor: pointer;'></i></a></h3>
  {% if excerpts %}
    {% for excerpt in excerpts %}
      {% if excerpt.status != 'rejected' %}
      <blockquote class="gray">
        <div class='flag'>
          {% flag_object excerpt %}
        </div>
        <p class='excerpt-content'>{{excerpt.content}}</p>
      </blockquote>
      {% endif %}
    {% endfor %}
  {% else %}

    <p class='text-muted'>No excerpts have been added from this reference.<br><em class='text-muted small'>Excerpts are snippets from publications that capture key information about a protein that does not easily fit into one of the existing fields (such as a summary, motivation, or observation).</em></p>

  {% endif %}
  <a class='text-info' data-toggle="modal" data-target="#excerptModal"><button class='btn btn-sm btn-secondary mt-1'><i class="fas fa-quote-left mr-2"></i></i>Add an excerpt</button></a>
</div>

{% endblock content %}


{% block modal %}

<div class="modal modal-center fade" id="excerptModal" tabindex="-1" role="dialog" aria-labelledby="excerptModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="excerptModalLongTitle"><strong>Add an excerpt from {{reference.citation}}</strong></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% if user.is_authenticated %}
      <form id="excerptModalForm" data-action-url="{% url 'references:add_excerpt' pk=reference.pk %}">
        {% csrf_token %}
        <div class="modal-body">
          <p>The excerpt might summarize the rationale for the a protein introduced in the paper, or capture a property or performance characteristic of the protein that does not easily fit into one of the existing fields.  Keep the message of each excerpt focused; you may add multiple excerpts for a given publication if necessary.<br><br><strong>Note: if the excerpt applies specifically to an individual protein, please enter the excerpt on that protein page instead.</strong></p>

          <div id="div_id_excerpt_content" class="form-group">
            <label for="id_excerpt_content" class="form-control-label">Excerpt content</label>
            <textarea class="form-control" name="excerpt_content" id="id_excerpt_content" rows="3" required="true"></textarea>
            <small class='text-muted'>Please note: inaccurate or inappropriate excerpts will be removed.</small>
          </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Add excerpt</button>
        </div>
      </form>
      {% else %}
      <div class="modal-body">
        <div>
          <p>You must be logged in to add excerpts to FPbase</p>
          <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}?next={% firstof request.path '/' %}">
            <button type="submit" class="btn btn-primary">sign in</button>
          </a>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
      {% endif %}
    </div>
  </div>
</div>

{% endblock modal %}

{% block extrafooter %}
    {% if request.user.is_staff %}
      {% load admin_urls %}
      <a href="{% url 'admin:references_reference_change' reference.id %}">{{ reference}} on admin</a><br>
    {% endif %}
{% endblock extrafooter %}


{% block javascript %}

    <script type="text/javascript">
      window.CSRF_TOKEN = "{{ csrf_token }}";
      $(document).on('show.bs.modal', '#excerptModal', function () {
          $('#excerptModal').css('z-index', 1200);
      });

      $(document).on('hidden.bs.modal', 'excerptModal', function () {
          $('#excerptModal').css('z-index', 1039);
      });
    </script>
{% endblock javascript %}

backend/references/templates/references/reference_list.html
{% extends "base.html" %}

{% block title %}Fluorescent Protein References{% endblock %}
{% block meta-description %}A list of all publications referenced at FPbase, the Fluorescent Protein Database{% endblock %}


{% block twitter_title %}Fluorescent Protein References at FPbase{% endblock twitter_title %}
{% block twitter_description %}A list of all publications referenced at FPbase, the Fluorescent Protein Database{% endblock twitter_description %}


{% block extrahead %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/jszip-2.5.0/dt-1.10.18/b-1.5.4/b-html5-1.5.4/fc-3.2.5/datatables.min.css"/>
<style>
  .table-header {
    white-space: nowrap;
  }
</style>
{% endblock extrahead %}

{% block container-class %}container-fluid referencelist{% endblock %}

{% block content %}

<div class='reftable-wrapper'>
  <h2 class='text-center'>Repeatome Reference List</h2>
  <div class="mb-3">
    <p class="small mb-2 mt-3">This is a table of all articles referenced on at least one page at repeatome.  Use the search field to search for any text in the table, including protein name, author name, journal name, publication year, or title contents.  1˚ proteins are intended to be proteins that were introduced by that reference, whereas 2˚ proteins were further characterized by that reference.  Click on any title, author, or protein, to see more info for that item at FPbase, or click on the "Link" <i class="fa fa-external-link-alt mx-1"></i> button to go to the publisher's website. </p>
  </div>

  <table class="table table-striped mt-4" id="referenceTable" style="width: 100%;">
    <thead>
      <tr class="table-header">
        <td>Link</td>
        <td>Year</td>
        <td>Journal</td>
        <td>Title</td>
        <td>Authors</td>
        <td>1˚ Proteins</td>
        <td>2˚ Proteins</td>
      </tr>
    </thead>
    <tbody>
      {% for ref in reference_list  %}
        <tr>
          <td class='text-center'><a href="https://doi.org/{{ ref.doi }}" target="_blank" rel="noopener"><i class="fas fa-external-link-alt text-secondary font-weight-bold"></i></a></td>
          <td class='text-center'>{{ref.year}}</td>
          <td>{{ ref.journal }}</td>
          <td><a href="{{ ref.get_absolute_url }}">{{ ref.title }}</a></td>
          <td class='authorlist'>
            {% for author in ref.authors.all %}
              <a href="{{ author.get_absolute_url }}">{{ author|title }}</a>{% if not forloop.last %},{% endif %}
            {% endfor %}
          </td>
          <td>
            {% for protein in ref.primary_proteins.all %}
              <a href="{{ protein.get_absolute_url }}">{{ protein.gene }}</a>{% if not forloop.last %},{% endif %}
            {% endfor %}
          </td>
          <!--<td>
            {% for protein in ref.proteins.all %}
              {% if protein not in ref.primary_proteins.all %}
                <a href="{{ protein.get_absolute_url }}">{{ protein.gene }}</a>{% if not forloop.last %},{% endif %}
              {% endif %}
            {% endfor %}
          </td>-->
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>


{% endblock content %}


{% block javascript %}
<script type="text/javascript" src="https://cdn.datatables.net/v/bs4/jszip-2.5.0/dt-1.10.18/b-1.5.4/b-html5-1.5.4/fc-3.2.5/datatables.min.js"></script>
<script>
  $(function() {
    $('#referenceTable').DataTable({
      "pageLength": 50,
      "scrollX": true,
      "lengthMenu": [ [10, 25, 50, 100, -1], [10, 25, 50, 100,"All"] ],
      "order": [[ 1, 'desc' ]],
      "columnDefs": [ {
        "targets": [0, -1],
        "orderable": false
      } ]
    });


  });
</script>
{% endblock javascript %}