backend/favit/urls.py
from django.urls import path

from favit import views

app_name = "favit"

urlpatterns = [
    path("add-or-remove", views.add_or_remove, name="add_or_remove"),
    path("remove", views.remove, name="remove"),
]

backend/proteins/api/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "api"

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/api.html"), name="api"),
    # /proteins/api
    # path("spectrum/", views.SpectrumList.as_view(), name="get-spectrum"),
    # path("spectrum/<int:pk>/", views.SpectrumDetail.as_view()),
    path("proteins/", views.ProteinListAPIView.as_view(), name="protein-api"),
    # path("proteins2/", views.ProteinListAPIView2.as_view(), name="protein-api2"),
    # path(
    #     "proteins/spectra/",
    #     views.ProteinSpectraListAPIView.as_view(),
    #     name="spectra-api",
    # ),
    path(
        "proteins/basic/",
        views.BasicProteinListAPIView.as_view(),
        name="basic-protein-api",
    ),
    # path("proteins/states/", views.StatesListAPIView.as_view(), name="states-api"),
    # /proteins/:slug/
    # re_path(
    #     r"^(?P<slug>[-\w]+)/$",
    #     views.ProteinRetrieveAPIView.as_view(),
    #     name="protein-api",
    # ),
    # non-normal endpoints
    # path("proteins/spectraslugs/", views.spectraslugs, name="spectra-slugs"),
    # path("proteins/ocinfo/", views.ocinfo, name="ocinfo"),
]

backend/proteins/urls.py
from os import getenv

from django.urls import path, re_path
from django.views.generic import TemplateView

from repeatome.decorators import login_required_message_and_redirect as login_required

from . import views

app_name = "proteins"

disabled = TemplateView.as_view(template_name="updates_disabled.html")

CONTRIBS_OPEN = not getenv("BLOCK_CONTRIBUTIONS")

urlpatterns = [
    # detail view: /:slug
    path("viewer/", views.microscopy_viewer, name='karyotype_viewer'),
    path("proteinTable/", views.ProteinTable, name="proteinTable"),
    path("repeatTable/", views.RepeatTable, name="repeatTable"),
    path("organismTable/", views.OrganismListView.as_view(), name="organismTable"),
    re_path(r"^search/", views.protein_search, name="search"),
    re_path(r"^blast/", views.blast_view, name="blast"),
    re_path(r"^karyotype_viewer", views.karyotype_view, name="karyotype_viewer"),
    re_path(
        r"^submit/",
        (
            login_required(
                views.ProteinCreateView.as_view(),
                message="You must be logged in to submit a new protein",
            )
            if CONTRIBS_OPEN
            else disabled
        ),
        name="submit",
    ),
    re_path(
        r"^protein/(?P<slug>[-\w]+)/update/",
        (
            login_required(
                views.ProteinUpdateView.as_view(),
                message="You must be logged in to update protein information",
            )
            if CONTRIBS_OPEN
            else disabled
        ),
        name="update",
    ),
    re_path(r"^table/", views.protein_table, name="table"),
    # url(r'^tree/(?P<organism>\d+)/$', views.protein_tree, name='tree'),
    path(
        "problems/",
        TemplateView.as_view(template_name="problems.html"),
        name="problems",
    ),
    path("problems/gaps/", views.problems_gaps, name="problems-gaps"),
    path(
        "problems/inconsistencies/",
        views.problems_inconsistencies,
        name="problems-inconsistencies",
    ),
    # path(
    #     "spectra/submit/",
    #     (
    #         login_required(
    #             views.SpectrumCreateView.as_view(),
    #             message="You must be logged in to submit a new spectrum",
    #         )
    #         if CONTRIBS_OPEN
    #         else disabled
    #     ),
    #     name="submit-spectra",
    # ),
    # path("spectra/submitted/", views.spectrum_submitted, name="spectrum_submitted"),
    # re_path(
    #     r"^spectra/submit/(?P<slug>[-\w]+)/$",
    #     (
    #         login_required(
    #             views.SpectrumCreateView.as_view(),
    #             message="You must be logged in to submit a new spectrum",
    #         )
    #         if CONTRIBS_OPEN
    #         else disabled
    #     ),
    #     name="submit-spectra",
    # ),
    # re_path(r"^spectra/(?P<slug>[-\w]+)", views.protein_spectra, name="spectra"),
    # path("spectra/", views.protein_spectra, name="spectra"),
    # path("spectra-graph/", views.protein_spectra_graph, name="spectra_graph"),
    # re_path(r"^spectra_csv/", views.spectra_csv, name="spectra_csv"),
    # re_path(
    #     r"^spectra_img/(?P<slug>[-\w]+)(\.(?P<extension>(png)|(svg)|(tif?f)|(pdf)|(jpe?g))?)?$",
    #     views.spectra_image,
    #     name="spectra-img",
    # ),
    # path(
    #     "spectra_url_builder/",
    #     TemplateView.as_view(template_name="spectrum_url_form.html"),
    #     name="spectra-url-builder",
    # ),
    # re_path(r"^fret/", views.fret_chart, name="fret"),
    # path("compare/", views.ComparisonView.as_view(), name="compare"),
    # re_path(
    #     r"^compare/(?P<proteins>[\w,\-]+)/$",
    #     views.ComparisonView.as_view(),
    #     name="compare",
    # ),
    # re_path(
    #     r"^lineage/",
    #     TemplateView.as_view(template_name="lineage.html"),
    #     name="lineage-list",
    # ),
    re_path(r"^chart/", TemplateView.as_view(template_name="ichart.html"), name="ichart"),
    re_path(
        r"^collections/(?P<owner>[\w.@+-]+)/?$",
        views.CollectionList.as_view(),
        name="collections",
    ),
    re_path(r"^collections/", views.CollectionList.as_view(), name="collections"),
    path(
        "collection/<int:pk>/",
        views.CollectionDetail.as_view(),
        name="collection-detail",
    ),
    re_path(
        r"^collection/(?P<pk>\d+)/update/",
        login_required(
            views.CollectionUpdateView.as_view(),
            message="You must be logged in to update collections",
        ),
        name="updatecollection",
    ),
    re_path(
        r"^collection/(?P<pk>\d+)/delete/",
        login_required(
            views.CollectionDeleteView.as_view(),
            message="You must be logged in to delete collections",
        ),
        name="deletecollection",
    ),
    re_path(
        r"^collection/create/",
        login_required(
            views.CollectionCreateView.as_view(),
            message="You must be logged in to create a new collection",
        ),
        name="newcollection",
    ),
    # path("activity", views.ActivityView.as_view(), name="activity"),
    # re_path(
    #     r"^protein/(?P<slug>[-\w]+)/$",
    #     views.ProteinDetailView.as_view(),
    #     name="protein-detail",
    # ),
    # path("organisms/", views.OrganismListView.as_view(), name="organism-list"),
    path(
        "organismTable/<int:pk>/",
        views.OrganismDetailView.as_view(),
        name="organismTable-detail",
    ),
    re_path(
       r"^proteinTable/(?P<slug>[-\w]+)/$", # slug is SlugField with name of gene
       # {'my_id': '?P<my_id>'}
       views.ProteinDetailView2.as_view(),
       name="proteinTable-detail",
    ),
    re_path(
       r"^repeatTable/(?P<slug>[-\w]+)/$", # slug is SlugField with name of repeat
       # {'my_id': '?P<my_id>'}
       views.RepeatDetailView.as_view(),
       name="repeatTable-detail",
    ),
    # re_path(
    #     r"^protein/(?P<slug>[-\w]+)/bleach/$",
    #     views.protein_bleach_formsets,
    #     name="protein-bleach-form",
    # ),
    re_path(
        r"^protein/(?P<slug>[-\w]+)/history/$",
        views.protein_history,
        name="protein-history",
    ),
    # re_path(
    #     r"^bleach_comparison/(?P<pk>[-\w]+)/$",
    #     views.bleach_comparison,
    #     name="bleach-comparison",
    # ),
    # path("bleach_comparison/", views.bleach_comparison, name="bleach-comparison"),
    # re_path(
    #     r"^protein/(?P<slug>[-\w]+)/rev/(?P<rev>\d+)$",
    #     views.ProteinDetailView.as_view(),
    #     name="protein-detail",
    # ),
    # re_path(
    #     r"^protein/(?P<slug>[-\w]+)/ver/(?P<ver>\d+)$",
    #     views.ProteinDetailView.as_view(),
    #     name="protein-detail",
    # ),
    path(
        "autocomplete-protein/",
        views.ProteinAutocomplete.as_view(),
        name="protein-autocomplete",
    ),
    path(
        "autocomplete-repeat/",
        views.RepeatAutocomplete.as_view(),
        name="repeat-autocomplete",
    ),
    # path(
    #     "autocomplete-lineage/",
    #     views.LineageAutocomplete.as_view(),
    #     name="lineage-autocomplete",
    # ),
    # path(
    #     "autocomplete-state/",
    #     views.StateAutocomplete.as_view(),
    #     name="state-autocomplete",
    # ),
    # path(
    #     "autocomplete-filter/",
    #     views.FilterAutocomplete.as_view(),
    #     name="filter-autocomplete",
    # ),
    # AJAX
    path("ajax/add_taxonomy/", views.add_organism, name="add_taxonomy"),
    # re_path(
    #     r"^ajax/filter_import/(?P<brand>[-\w]+)$",
    #     views.filter_import,
    #     name="filter_import",
    # ),
    re_path(
        r"^ajax/add_protein_reference/(?P<slug>[-\w]+)/$",
        views.add_reference,
        name="add_protein_reference",
    ),
    re_path(
        r"^ajax/add_protein_excerpt/(?P<slug>[-\w]+)/$",
        views.add_protein_excerpt,
        name="add_protein_excerpt",
    ),
    re_path(
        r"^ajax/admin_approve_protein/(?P<slug>[-\w]+)/$",
        views.approve_protein,
        name="admin_approve_protein",
    ),
    path(
        "ajax/admin_revert_version/<int:ver>",
        views.revert_version,
        name="admin_revert_version",
    ),
    path(
        "ajax/admin_revert_revision/<int:rev>",
        views.revert_revision,
        name="admin_revert_revision",
    ),
    # re_path(
    #     r"^ajax/update_transitions/(?P<slug>[-\w]+)/$",
    #     views.update_transitions,
    #     name="update_transitions",
    # ),
    path(
        "ajax/validate_proteinname/",
        views.validate_proteinname,
        name="validate_proteinname",
    ),
    # path(
    #     "ajax/validate_spectrumownername/",
    #     views.similar_spectrum_owners,
    #     name="validate_spectrumownername",
    # ),
    path(
        "ajax/remove_from_collection/",
        views.collection_remove,
        name="collection-remove",
    ),
    path("ajax/flag_object/", views.flag_object, name="flag_object"),
    path("ajax/add_to_collection/", views.add_to_collection, name="add_to_collection"),
    path("ajax/comparison/", views.update_comparison, name="update-comparison"),
    # re_path(r"^ajax/lineage/(?P<slug>[-\w]+)/$", views.get_lineage, name="get-lineage"),
    # path("ajax/lineage/", views.get_lineage, name="get-lineage"),
    # re_path(
    #     r"^ajax/org_lineage/(?P<org>[-\w]+)/$",
    #     views.get_lineage,
    #     name="get-org-lineage",
    # ),
    # re_path(
    #     r"^microscope/(?P<pk>[-\w]+)/report/json/$",
    #     views.scope_report_json,
    #     name="scope_report_json",
    # ),
    # re_path(r"^widget/(?P<slug>[-\w]+)/$", views.Widget.as_view(), name="widget-detail"),
]

backend/repeatome/users/urls.py
from django.contrib.admin.views.decorators import staff_member_required
from django.urls import path, re_path

from . import views

app_name = "users"
urlpatterns = [
    path(
        "",
        view=staff_member_required(views.UserListView.as_view()),
        name="list",
    ),
    re_path(r"^~redirect/$", view=views.UserRedirectView.as_view(), name="redirect"),
    re_path(r"^~update/$", view=views.UserUpdateView.as_view(), name="update"),
    re_path(
        r"^(?P<username>[\w.@+-]+)/$",
        view=views.UserDetailView.as_view(),
        name="detail",
    ),
]

backend/proteins/api/views.py
from django.db.models import F, Max
from django.http import HttpResponse
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django_filters import rest_framework as filters
from rest_framework.generics import (
    ListAPIView,
    RetrieveAPIView,
    RetrieveUpdateDestroyAPIView,
)
from rest_framework.permissions import AllowAny, IsAdminUser, IsAuthenticated
from rest_framework.settings import api_settings
from rest_framework_csv import renderers as r

from ..filters import ProteinFilter
from ..models import ProteinTF
from .serializers import (
    BasicProteinSerializer,
    ProteinSerializer,
    ProteinSerializer2,
)

class ProteinListAPIView2(ListAPIView):
    # queryset = ProteinTF.objects.all().prefetch_related("states", "transitions")
    queryset = ProteinTF.objects.all()
    permission_classes = (AllowAny,)
    serializer_class = ProteinSerializer2
    lookup_field = "slug"  # Don't use Protein.id!
    filter_backends = (filters.DjangoFilterBackend,)
    filterset_class = ProteinFilter
    renderer_classes = [r.CSVRenderer, *api_settings.DEFAULT_RENDERER_CLASSES]

    @method_decorator(cache_page(60 * 10))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class ProteinListAPIView(ListAPIView):
    # queryset = ProteinTF.objects.all().prefetch_related("states", "transitions").select_related("default_state")
    queryset = ProteinTF.objects.all()
    permission_classes = (AllowAny,)
    serializer_class = ProteinSerializer
    lookup_field = "slug"  # Don't use Protein.id!
    filter_backends = (filters.DjangoFilterBackend,)
    filterset_class = ProteinFilter
    renderer_classes = [r.CSVRenderer, *api_settings.DEFAULT_RENDERER_CLASSES]

    @method_decorator(cache_page(60 * 10))
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)


class BasicProteinListAPIView(ProteinListAPIView):
    queryset = (
        ProteinTF.objects.filter()
        # .select_related("default_state")
        # .annotate(rate=Max(F("default_state__bleach_measurements__rate")))
    )
    permission_classes = (AllowAny,)
    serializer_class = BasicProteinSerializer


class ProteinRetrieveUpdateDestroyAPIView(RetrieveUpdateDestroyAPIView):
    queryset = ProteinTF.objects.all()
    permission_classes = (IsAdminUser,)
    serializer_class = ProteinSerializer
    lookup_field = "slug"  # Don't use Protein.id


class ProteinRetrieveAPIView(RetrieveAPIView):
    queryset = ProteinTF.objects.all()
    permission_classes = (AllowAny,)
    serializer_class = ProteinSerializer
    lookup_field = "slug"  # Don't use Protein.id

backend/proteins/views/autocomplete.py
from dal import autocomplete

from ..models import ProteinTF, Repeat

# from django.contrib.postgres.search import TrigramSimilarity


class ProteinAutocomplete(autocomplete.Select2QuerySetView):
    def get_results(self, context):
        """Return data for the 'results' key of the response."""
        return [
            {
                "id": result.id,
                # 'slug': result.slug,
                "text": result.gene,
            }
            for result in context["object_list"]
        ]

    def get_queryset(self):
        qs = ProteinTF.objects.all()
        if self.q:
            qs = qs.filter(gene__icontains=self.q)
        return qs

class RepeatAutocomplete(autocomplete.Select2QuerySetView):
    def get_results(self, context):
        """Return data for the 'results' key of the response."""
        return [
            {
                "id": result.id,
                'slug': result.slug,
                "text": result.name,
            }
            for result in context["object_list"]
        ]

    def get_queryset(self):
        qs = Repeat.objects.all()
        if self.q:
            qs = qs.filter(name__icontains=self.q)
        return qs



# class FilterAutocomplete(autocomplete.Select2QuerySetView):
#     def get_queryset(self):
#         # Don't forget to filter out results depending on the visitor !
#         # if not self.request.user.is_authenticated:
#         #     return Filter.objects.none()
#         qs = Filter.objects.all()
#         if self.q:
#             # qs = Filter.objects.annotate(
#             #     similarity=TrigramSimilarity('part', self.q)) \
#             #     .filter(similarity__gt=0.3) \
#             #     .order_by('-similarity')
#             qs = qs.filter(name__icontains=self.q)
#         return qs

backend/proteins/views/blast.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import ensure_csrf_cookie

from repeatome.util import is_ajax

from ..util.blast import blast


@ensure_csrf_cookie
def blast_view(request):
    if not is_ajax(request):
        return render(request, "proteins/blast.html")

    seq = request.POST.get("query")
    binary = request.POST.get("binary", "blastp")
    assert binary in ("blastx", "blastp")
    if seq:
        try:
            result = blast(seq, binary)
            return JsonResponse({"status": 200, "blastResult": result})
        except Exception as e:
            return JsonResponse({"status": 500, "error": f"BLAST error: {e}"})
    return JsonResponse({"status": 204, "blastResult": []})

backend/proteins/views/karyotype.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import ensure_csrf_cookie

from repeatome.util import is_ajax

from ..util.blast import blast


def karyotype_view(request):
    return render(request, "proteins/karyotype_viewer.html")

backend/proteins/views/mixins.py
class OwnableObject:
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def attach_owner(self, form):
        self.object = form.save(commit=False)
        if not self.object.owner:
            self.object.owner = self.request.user
        self.object.save()

backend/proteins/templates/proteins/modals/_add_to_collection_modal.html
{% load i18n %}

<div class="modal fade" id="collectionModal" tabindex="-1" role="dialog" aria-labelledby="collectionModalTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="collectionModalLongTitle"><strong>Add {{ protein.name }} to your collection</strong></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% if user.is_authenticated %}
      <div class="container">
        <p class='mt-4' id="currentmemberships"></p>
    		<form id="collectionForm" class='mt-4 mb-2' data-action-url="{% url 'proteins:add_to_collection' %}">
          <div class="input-group" id="collectionSelection">
              <div class="input-group-append">
                <button class="btn btn-info" type="submit" >Add</button>
              </div>
          </div>
          <input type="hidden" name="protein" class='hidden' value="{{ protein.id }}">
          {% csrf_token %}
    		</form>
        <p class='mb-2 mt-3 small' style='color:gray'><em> <a href="{% url 'proteins:newcollection' %}?next={% firstof request.path '/' %}">Create a new collection</a> or edit your collections on <a href="{% url 'users:detail' request.user.username %}">your profile</a></em></p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
	  {% else %}
  	      <div class="modal-body">
  	      	<div>
  	      		<p>You must be logged in to create protein collections</p>
  	      		<a id="log-in-link" class="nav-link" href="{% url 'account_login' %}?next={% firstof request.path '/' %}"><button type="submit" class="btn btn-primary">{% trans "sign in" %}</button></a>
  	      	</div>
  	      </div>
  	      <div class="modal-footer">
  	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
  	      </div>
	  {% endif %}
    </div>
  </div>
</div>

backend/proteins/templates/proteins/modals/_excerpt_modal.html
{% load i18n %}

<div class="modal fade" id="excerptModal" tabindex="-1" role="dialog" aria-labelledby="excerptModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="excerptModalLongTitle"><strong>Add an excerpt</strong></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% if user.is_authenticated %}
      <form id="excerptModalForm" data-action-url="{% url 'proteins:add_protein_excerpt' slug=protein.slug %}">
        {% csrf_token %}
        <div class="modal-body">
          <p>Add a brief excerpt from a publication that discusses {{ protein.name }}. The excerpt might summarize the rationale for the protein, or capture a property or performance characteristic of the protein that does not easily fit into one of the existing fields.  Keep the message of each excerpt focused; you may add multiple excerpts for a given publication if necessary.</p>

          <div id="div_id_excerpt_content" class="form-group">
            <label for="id_excerpt_content" class="form-control-label">Excerpt content</label>
            <textarea class="form-control" name="excerpt_content" id="id_excerpt_content" rows="3" required="true"></textarea>
            <small class='text-muted'>Please note: inaccurate or inappropriate excerpts will be removed.</small>
          </div>

          <div id="div_id_excerpt_doi" class="form-group">
            <label for="id_excerpt_doi" class="form-control-label">Excerpt DOI</label>
            <div class="">
              <input type="text" name="excerpt_doi" maxlength="100" class="textinput textInput form-control" required="" id="id_excerpt_doi" pattern="10.\d{4,9}/[-._;()/:a-zA-Z0-9]+" oninvalid="setCustomValidity('Not a valid DOI string')" oninput="setCustomValidity('')">
            </div>
            <small id="hint_id_excerpt_doi" class="text-muted">e.g. 10.1038/nmeth.2413</small>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Add excerpt</button>
        </div>
      </form>
      {% else %}
      <div class="modal-body">
        <div>
          <p>You must be logged in to add excerpts to FPbase</p>
          <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}?next={% firstof request.path '/' %}">
            <button type="submit" class="btn btn-primary">{% trans "sign in" %}</button>
          </a>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
      {% endif %}
    </div>
  </div>
</div>

backend/proteins/templates/proteins/modals/_organism_modal.html
{% load i18n %}

<div class="modal modal-center fade" id="organismModal" tabindex="-1" role="dialog" aria-labelledby="organismModalTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="organismModalLongTitle"><strong>Add an Organism</strong></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% if user.is_authenticated %}
      <form id="taxonomyModalForm" data-action-url="{% url 'proteins:add_taxonomy' %}">
        {% csrf_token %}
        <div class="modal-body">
          <p>Enter the <a href="https://www.ncbi.nlm.nih.gov/taxonomy">NCBI Taxonomy ID</a> for the organism you would like to add.</p>
          <div id="div_id_taxonomy_id" class="form-group">
            <label for="id_taxonomy_id" class="form-control-label">Taxonomy ID</label>
            <div class="">
              <input type="number" name="taxonomy_id" min="1" max="9999999" class="textinput textInput form-control" id="id_taxonomy_id" required>
            </div>
            <small id="hint_id_taxonomy_id" class="text-muted">e.g. 6100</small>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Add Organism</button>
        </div>
      </form>
      {% else %}
      <div class="modal-body">
        <div>
          <p>You must be logged in to add references to FPbase</p>
          <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}?next={% firstof request.path '/' %}">
            <button type="submit" class="btn btn-primary">{% trans "sign in" %}</button>
          </a>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
      {% endif %}
    </div>
  </div>
</div>

backend/proteins/templates/proteins/modals/_reference_modal.html
{% load i18n %}

<div class="modal fade" id="referenceModal" tabindex="-1" role="dialog" aria-labelledby="referenceModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="referenceModalLongTitle"><strong>Add a reference</strong></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% if user.is_authenticated %}
      <form id="refModalForm" data-action-url="{% url 'proteins:add_protein_reference' slug=protein.slug %}">
        {% csrf_token %}
        <div class="modal-body">
          <p>Add a publication that references {{ protein.name }}. It does not need to be the paper that introduced the protein, but it should further characterize the properties or performance of the protein specifically. (Please do not add a paper that simply mentions the protein in the methods, if the performance of the protein is not discussed anywhere in the paper).</p>
          <div id="div_id_reference_doi" class="form-group">
            <label for="id_reference_doi" class="form-control-label">Reference DOI</label>
            <div class="">
              <input type="text" name="reference_doi" maxlength="100" class="textinput textInput form-control" required="" id="id_reference_doi" pattern="10.\d{4,9}/[-._;()/:a-zA-Z0-9]+" oninvalid="setCustomValidity('Not a valid DOI string')" oninput="setCustomValidity('')">
            </div>
            <small id="hint_id_reference_doi" class="text-muted">e.g. 10.1038/nmeth.2413</small>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Add reference</button>
        </div>
      </form>
      {% else %}
      <div class="modal-body">
        <div>
          <p>You must be logged in to add references to FPbase</p>
          <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}?next={% firstof request.path '/' %}">
            <button type="submit" class="btn btn-primary">{% trans "sign in" %}</button>
          </a>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
      {% endif %}
    </div>
  </div>
</div>

backend/proteins/templates/proteins/modals/_state_transition_modal.html
{% load i18n %}

<div class="modal fade" id="transitionModal" tabindex="-1" role="dialog" aria-labelledby="transitionModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="transitionModalLongTitle"><strong>Edit {{ protein.name }} Transitions</strong></h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      {% if user.is_authenticated %}
      <div class="container">
      	<p class='mt-2 small'><em>If you need to add states, please use the <a href="{% url 'proteins:update' slug=protein.slug %}" class='text-secondary'>protein update form</a> first, then return to this form.</em></p>
      		<form id="transitionForm" class='mt-2' data-action-url="{% url 'proteins:update_transitions' slug=protein.slug %}">
            <input type="hidden" name="protein" value="{{ protein.slug }}">
      		</form>
          </div>
	  {% else %}
  	      <div class="modal-body">
  	      	<div>
  	      		<p>You must be logged in to make transition updates</p>
  	      		<a id="log-in-link" class="nav-link" href="{% url 'account_login' %}?next={% firstof request.path '/' %}"><button type="submit" class="btn btn-primary">{% trans "sign in" %}</button></a>
  	      	</div>
  	      </div>
  	      <div class="modal-footer">
  	        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
  	      </div>
	  {% endif %}
    </div>
  </div>
</div>