backend/favit/urls.py
from django.urls import path

from favit import views

app_name = "favit"

urlpatterns = [
    path("add-or-remove", views.add_or_remove, name="add_or_remove"),
    path("remove", views.remove, name="remove"),
]

backend/proteins/urls.py
from os import getenv

from django.urls import path, re_path
from django.views.generic import TemplateView

from repeatome.decorators import login_required_message_and_redirect as login_required

from . import views

app_name = "proteins"

disabled = TemplateView.as_view(template_name="updates_disabled.html")

CONTRIBS_OPEN = not getenv("BLOCK_CONTRIBUTIONS")

urlpatterns = [
    # detail view: /:slug
    path("viewer/", views.microscopy_viewer, name='karyotype_viewer'),
    path("proteinTable/", views.ProteinTable, name="proteinTable"),
    path("repeatTable/", views.RepeatTable, name="repeatTable"),
    path("organismTable/", views.OrganismListView.as_view(), name="organismTable"),
    re_path(r"^search/", views.protein_search, name="search"),
    re_path(r"^blast/", views.blast_view, name="blast"),
    re_path(r"^karyotype_viewer", views.karyotype_view, name="karyotype_viewer"),
    re_path(
        r"^submit/",
        (
            login_required(
                views.ProteinCreateView.as_view(),
                message="You must be logged in to submit a new protein",
            )
            if CONTRIBS_OPEN
            else disabled
        ),
        name="submit",
    ),
    re_path(
        r"^protein/(?P<slug>[-\w]+)/update/",
        (
            login_required(
                views.ProteinUpdateView.as_view(),
                message="You must be logged in to update protein information",
            )
            if CONTRIBS_OPEN
            else disabled
        ),
        name="update",
    ),
    re_path(r"^table/", views.protein_table, name="table"),
    # url(r'^tree/(?P<organism>\d+)/$', views.protein_tree, name='tree'),
    path(
        "problems/",
        TemplateView.as_view(template_name="problems.html"),
        name="problems",
    ),
    path("problems/gaps/", views.problems_gaps, name="problems-gaps"),
    path(
        "problems/inconsistencies/",
        views.problems_inconsistencies,
        name="problems-inconsistencies",
    ),
    # path(
    #     "spectra/submit/",
    #     (
    #         login_required(
    #             views.SpectrumCreateView.as_view(),
    #             message="You must be logged in to submit a new spectrum",
    #         )
    #         if CONTRIBS_OPEN
    #         else disabled
    #     ),
    #     name="submit-spectra",
    # ),
    # path("spectra/submitted/", views.spectrum_submitted, name="spectrum_submitted"),
    # re_path(
    #     r"^spectra/submit/(?P<slug>[-\w]+)/$",
    #     (
    #         login_required(
    #             views.SpectrumCreateView.as_view(),
    #             message="You must be logged in to submit a new spectrum",
    #         )
    #         if CONTRIBS_OPEN
    #         else disabled
    #     ),
    #     name="submit-spectra",
    # ),
    # re_path(r"^spectra/(?P<slug>[-\w]+)", views.protein_spectra, name="spectra"),
    # path("spectra/", views.protein_spectra, name="spectra"),
    # path("spectra-graph/", views.protein_spectra_graph, name="spectra_graph"),
    # re_path(r"^spectra_csv/", views.spectra_csv, name="spectra_csv"),
    # re_path(
    #     r"^spectra_img/(?P<slug>[-\w]+)(\.(?P<extension>(png)|(svg)|(tif?f)|(pdf)|(jpe?g))?)?$",
    #     views.spectra_image,
    #     name="spectra-img",
    # ),
    # path(
    #     "spectra_url_builder/",
    #     TemplateView.as_view(template_name="spectrum_url_form.html"),
    #     name="spectra-url-builder",
    # ),
    # re_path(r"^fret/", views.fret_chart, name="fret"),
    # path("compare/", views.ComparisonView.as_view(), name="compare"),
    # re_path(
    #     r"^compare/(?P<proteins>[\w,\-]+)/$",
    #     views.ComparisonView.as_view(),
    #     name="compare",
    # ),
    # re_path(
    #     r"^lineage/",
    #     TemplateView.as_view(template_name="lineage.html"),
    #     name="lineage-list",
    # ),
    re_path(r"^chart/", TemplateView.as_view(template_name="ichart.html"), name="ichart"),
    re_path(
        r"^collections/(?P<owner>[\w.@+-]+)/?$",
        views.CollectionList.as_view(),
        name="collections",
    ),
    re_path(r"^collections/", views.CollectionList.as_view(), name="collections"),
    path(
        "collection/<int:pk>/",
        views.CollectionDetail.as_view(),
        name="collection-detail",
    ),
    re_path(
        r"^collection/(?P<pk>\d+)/update/",
        login_required(
            views.CollectionUpdateView.as_view(),
            message="You must be logged in to update collections",
        ),
        name="updatecollection",
    ),
    re_path(
        r"^collection/(?P<pk>\d+)/delete/",
        login_required(
            views.CollectionDeleteView.as_view(),
            message="You must be logged in to delete collections",
        ),
        name="deletecollection",
    ),
    re_path(
        r"^collection/create/",
        login_required(
            views.CollectionCreateView.as_view(),
            message="You must be logged in to create a new collection",
        ),
        name="newcollection",
    ),
    # path("activity", views.ActivityView.as_view(), name="activity"),
    # re_path(
    #     r"^protein/(?P<slug>[-\w]+)/$",
    #     views.ProteinDetailView.as_view(),
    #     name="protein-detail",
    # ),
    # path("organisms/", views.OrganismListView.as_view(), name="organism-list"),
    path(
        "organismTable/<int:pk>/",
        views.OrganismDetailView.as_view(),
        name="organismTable-detail",
    ),
    re_path(
       r"^proteinTable/(?P<slug>[-\w]+)/$", # slug is SlugField with name of gene
       # {'my_id': '?P<my_id>'}
       views.ProteinDetailView2.as_view(),
       name="proteinTable-detail",
    ),
    re_path(
       r"^repeatTable/(?P<slug>[-\w]+)/$", # slug is SlugField with name of repeat
       # {'my_id': '?P<my_id>'}
       views.RepeatDetailView.as_view(),
       name="repeatTable-detail",
    ),
    # re_path(
    #     r"^protein/(?P<slug>[-\w]+)/bleach/$",
    #     views.protein_bleach_formsets,
    #     name="protein-bleach-form",
    # ),
    re_path(
        r"^protein/(?P<slug>[-\w]+)/history/$",
        views.protein_history,
        name="protein-history",
    ),
    # re_path(
    #     r"^bleach_comparison/(?P<pk>[-\w]+)/$",
    #     views.bleach_comparison,
    #     name="bleach-comparison",
    # ),
    # path("bleach_comparison/", views.bleach_comparison, name="bleach-comparison"),
    # re_path(
    #     r"^protein/(?P<slug>[-\w]+)/rev/(?P<rev>\d+)$",
    #     views.ProteinDetailView.as_view(),
    #     name="protein-detail",
    # ),
    # re_path(
    #     r"^protein/(?P<slug>[-\w]+)/ver/(?P<ver>\d+)$",
    #     views.ProteinDetailView.as_view(),
    #     name="protein-detail",
    # ),
    path(
        "autocomplete-protein/",
        views.ProteinAutocomplete.as_view(),
        name="protein-autocomplete",
    ),
    path(
        "autocomplete-repeat/",
        views.RepeatAutocomplete.as_view(),
        name="repeat-autocomplete",
    ),
    # path(
    #     "autocomplete-lineage/",
    #     views.LineageAutocomplete.as_view(),
    #     name="lineage-autocomplete",
    # ),
    # path(
    #     "autocomplete-state/",
    #     views.StateAutocomplete.as_view(),
    #     name="state-autocomplete",
    # ),
    # path(
    #     "autocomplete-filter/",
    #     views.FilterAutocomplete.as_view(),
    #     name="filter-autocomplete",
    # ),
    # AJAX
    path("ajax/add_taxonomy/", views.add_organism, name="add_taxonomy"),
    # re_path(
    #     r"^ajax/filter_import/(?P<brand>[-\w]+)$",
    #     views.filter_import,
    #     name="filter_import",
    # ),
    re_path(
        r"^ajax/add_protein_reference/(?P<slug>[-\w]+)/$",
        views.add_reference,
        name="add_protein_reference",
    ),
    re_path(
        r"^ajax/add_protein_excerpt/(?P<slug>[-\w]+)/$",
        views.add_protein_excerpt,
        name="add_protein_excerpt",
    ),
    re_path(
        r"^ajax/admin_approve_protein/(?P<slug>[-\w]+)/$",
        views.approve_protein,
        name="admin_approve_protein",
    ),
    path(
        "ajax/admin_revert_version/<int:ver>",
        views.revert_version,
        name="admin_revert_version",
    ),
    path(
        "ajax/admin_revert_revision/<int:rev>",
        views.revert_revision,
        name="admin_revert_revision",
    ),
    # re_path(
    #     r"^ajax/update_transitions/(?P<slug>[-\w]+)/$",
    #     views.update_transitions,
    #     name="update_transitions",
    # ),
    path(
        "ajax/validate_proteinname/",
        views.validate_proteinname,
        name="validate_proteinname",
    ),
    # path(
    #     "ajax/validate_spectrumownername/",
    #     views.similar_spectrum_owners,
    #     name="validate_spectrumownername",
    # ),
    path(
        "ajax/remove_from_collection/",
        views.collection_remove,
        name="collection-remove",
    ),
    path("ajax/flag_object/", views.flag_object, name="flag_object"),
    path("ajax/add_to_collection/", views.add_to_collection, name="add_to_collection"),
    path("ajax/comparison/", views.update_comparison, name="update-comparison"),
    # re_path(r"^ajax/lineage/(?P<slug>[-\w]+)/$", views.get_lineage, name="get-lineage"),
    # path("ajax/lineage/", views.get_lineage, name="get-lineage"),
    # re_path(
    #     r"^ajax/org_lineage/(?P<org>[-\w]+)/$",
    #     views.get_lineage,
    #     name="get-org-lineage",
    # ),
    # re_path(
    #     r"^microscope/(?P<pk>[-\w]+)/report/json/$",
    #     views.scope_report_json,
    #     name="scope_report_json",
    # ),
    # re_path(r"^widget/(?P<slug>[-\w]+)/$", views.Widget.as_view(), name="widget-detail"),
]

backend/fpbase/forms.py
from allauth.account.forms import SignupForm
# Use below for python 13
from django_recaptcha.fields import ReCaptchaField
from django_recaptcha.widgets import ReCaptchaV3
# Use below for python 3.11
# from captcha.fields import ReCaptchaField
# from captcha.widgets import ReCaptchaV3
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms
from django.conf import settings
from django.core.mail import EmailMessage
from django.utils.html import escape
from django.utils.safestring import mark_safe


class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    message = forms.CharField(widget=forms.Textarea)
    captcha = ReCaptchaField(label="", widget=ReCaptchaV3(attrs={"required_score": 0.85}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.add_input(Submit("submit", "Submit", css_class="btn btn-primary"))
        self.helper.form_method = "POST"

    def friendly_email(self):
        fullname = self.cleaned_data["name"]
        address = self.cleaned_data["email"]
        return mark_safe("%s <%s>") % (escape(fullname), escape(address))

    def send_email(self):
        EmailMessage(
            f"FPbase contact from {self.cleaned_data['name']}",
            self.cleaned_data["message"],
            to=[a[1] for a in settings.ADMINS],
            headers={"Reply-To": self.friendly_email()},
        ).send()


class CustomSignupForm(SignupForm):
    # only if not in debug mode
    if not settings.DEBUG:
        captcha = ReCaptchaField(label="", widget=ReCaptchaV3(attrs={"required_score": 0.85}))
    field_order = ["username", "email", "password1", "password2", "captcha"]

backend/fpbase/views.py
from django.conf import settings
from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import render
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView
from django.views.generic.edit import FormView
from sentry_sdk import last_event_id

from fpbase.forms import ContactForm
from proteins.models import Protein, Spectrum, ProteinTF


class HomeView(TemplateView):
    template_name = "pages/home.html"

    def get_context_data(self):
        data = super().get_context_data()
        data["stats"] = {
            "proteins": Protein.objects.count(),
            "protspectra": Spectrum.objects.exclude(owner_state=None).count(),
        }
        return data


class ContactView(FormView):
    template_name = "pages/contact.html"
    form_class = ContactForm
    success_url = "/thanks/"

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        form.send_email()
        return super().form_valid(form)

@staff_member_required
def test500(request):
    # Return an "Internal Server Error" 500 response code.
    raise Exception("Make response code 500!")


def server_error(request, *args, **argv):
    return render(
        request,
        "500.html",
        {
            "sentry_event_id": last_event_id(),
            "sentry_dsn": getattr(settings, "SENTRY_DSN", ""),
        },
        status=500,
    )


@cache_page(10)
def testview(request):
    import logging

    logger = logging.getLogger(__name__)
    p = Protein.objects.get(name="mNeonGreen")
    logger.info(p)
    return render(request, "pages/test.html", {"protein": p})

backend/fpbase/templates/pages/home.html
{% extends "base.html" %}
{% load webp_picture from protein_tags %}
{% load static %}

{% block meta-description %}RepeatOme is a moderated, user-editable fluorescent protein database designed by microscopists.  Search, share, and organize information about fluorescent proteins and their characteristics.{% endblock %}


{% block extrahead %}
<style>
  .cover-wrapper {
    background: no-repeat center center;
    background-image: url("{% static 'images/home_img_2.png' %}");
  }
</style>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@algolia/autocomplete-theme-classic" />
<script src="https://cdn.jsdelivr.net/npm/algoliasearch@4/dist/algoliasearch-lite.umd.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@algolia/autocomplete-js@1.19.2/dist/umd/index.production.js" integrity="sha256-pJWTMvqlBlMBxdkM5bI1ScIVC7LFJoCplF0qQtcL62s=" crossorigin="anonymous"></script>
<script>
  const { autocomplete } = window['@algolia/autocomplete-js'];
</script>
<script type='module' src="{% static 'algolia2.js' %}" defer></script>
<script src="{% static 'search_logic.js' %}"></script>
{% endblock extrahead %}

{% block body-class %}home-body{% endblock body-class %}
{% block body %}
<div class="cover-wrapper">
  <div class="cover-wrapper-inner">
    <nav class="navbar navbar-expand-sm navbar-dark bg-transparent fixed-top">
      {% block navcontainer %} {% include "_nav.html" %} {% endblock navcontainer %}
    </nav>
    <noscript>
        <div class="container text-center mt-0 bg-dark text-white pt-3 pb-4"><p><strong>Javascript is disabled!&nbsp;  Many pages and features of FPbase will not work properly</strong></p>
          <form class="input-group home-search" method="get" action="/search/">
            <input type="search" class="form-control" name="name__icontains" placeholder="Protein name, accession, doi, organism, author...">
            <span class="input-group-append">
              <button class="btn btn-secondary" type="submit">search</button>
            </span>
          </form>
        </div>
    </noscript>
        <main role="main" class="cover-container container">
          <div class="row">
            <div class="col-md-7 mt-lg-5 search-col order-sm-2 search-col">
              <h1 class="cover-heading text-center mb-4">Find a Protein or a Satellite</h1>
                <form class="input-group" method="get" action="/search/">
                  <input class="form-control algolia-searchbar" id="algolia-search-input" name="q" type="search" placeholder='Search' autocomplete="off"/>
                </form>
                <p class="m-t-4 advanced-search"><a href="{% url 'proteins:search' %}">advanced search</a></p>
            </div>
            <div class="col-md-4  order-sm-1" id="protein-image">
              <div style="position: absolute;" class="no-glow"> {% comment %} top:-70px {% endcomment %}
                {% webp_picture 'images/home_img_2.png' 'img-fluid' "EGFP image" %}
              </div>
              <div style="display: none; position: absolute; " class="glow"> {% comment %} top:-70px {% endcomment %}
                {% webp_picture 'images/home_img_2.png' 'img-fluid' "glowing EGFP image" %}
              </div>
            </div>
          </div>

        </main>
    <div class="home-stats">
        <span>
          {% webp_picture 'images/gfp_white_40.png' 'gfpicon' 'white gfp icon' %}{{stats.proteins}} <a href="{% url 'proteins:table' %}" class='text-white'>Proteins</a>
        </span>
        <span>
          <i class="fas fa-chart-area mr-2" ></i>{{stats.protspectra}} <a href="{% url 'proteins:spectra' %}" class='text-white'>Repeats</a>
        </span>
    </div>

  </div>

    <!-- cover-wrapper-inner -->
</div>
<!-- cover-wrapper -->
{% endblock body %}