backend/favit/urls.py
from django.urls import path

from favit import views

app_name = "favit"

urlpatterns = [
    path("add-or-remove", views.add_or_remove, name="add_or_remove"),
    path("remove", views.remove, name="remove"),
]

backend/proteins/api/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "api"

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/api.html"), name="api"),
    # /proteins/api
    # path("spectrum/", views.SpectrumList.as_view(), name="get-spectrum"),
    # path("spectrum/<int:pk>/", views.SpectrumDetail.as_view()),
    path("proteins/", views.ProteinListAPIView.as_view(), name="protein-api"),
    # path("proteins2/", views.ProteinListAPIView2.as_view(), name="protein-api2"),
    # path(
    #     "proteins/spectra/",
    #     views.ProteinSpectraListAPIView.as_view(),
    #     name="spectra-api",
    # ),
    path(
        "proteins/basic/",
        views.BasicProteinListAPIView.as_view(),
        name="basic-protein-api",
    ),
    # path("proteins/states/", views.StatesListAPIView.as_view(), name="states-api"),
    # /proteins/:slug/
    # re_path(
    #     r"^(?P<slug>[-\w]+)/$",
    #     views.ProteinRetrieveAPIView.as_view(),
    #     name="protein-api",
    # ),
    # non-normal endpoints
    # path("proteins/spectraslugs/", views.spectraslugs, name="spectra-slugs"),
    # path("proteins/ocinfo/", views.ocinfo, name="ocinfo"),
]

backend/proteins/urls.py
from os import getenv

from django.urls import path, re_path
from django.views.generic import TemplateView

from repeatome.decorators import login_required_message_and_redirect as login_required

from . import views

app_name = "proteins"

disabled = TemplateView.as_view(template_name="updates_disabled.html")

CONTRIBS_OPEN = not getenv("BLOCK_CONTRIBUTIONS")

urlpatterns = [
    # detail view: /:slug
    path("viewer/", views.microscopy_viewer, name='karyotype_viewer'),
    path("proteinTable/", views.ProteinTable, name="proteinTable"),
    path("repeatTable/", views.RepeatTable, name="repeatTable"),
    path("organismTable/", views.OrganismListView.as_view(), name="organismTable"),
    re_path(r"^search/", views.protein_search, name="search"),
    re_path(r"^blast/", views.blast_view, name="blast"),
    re_path(r"^karyotype_viewer", views.karyotype_view, name="karyotype_viewer"),
    re_path(
        r"^submit/",
        (
            login_required(
                views.ProteinCreateView.as_view(),
                message="You must be logged in to submit a new protein",
            )
            if CONTRIBS_OPEN
            else disabled
        ),
        name="submit",
    ),
    re_path(
        r"^protein/(?P<slug>[-\w]+)/update/",
        (
            login_required(
                views.ProteinUpdateView.as_view(),
                message="You must be logged in to update protein information",
            )
            if CONTRIBS_OPEN
            else disabled
        ),
        name="update",
    ),
    re_path(r"^table/", views.protein_table, name="table"),
    # url(r'^tree/(?P<organism>\d+)/$', views.protein_tree, name='tree'),
    path(
        "problems/",
        TemplateView.as_view(template_name="problems.html"),
        name="problems",
    ),
    path("problems/gaps/", views.problems_gaps, name="problems-gaps"),
    path(
        "problems/inconsistencies/",
        views.problems_inconsistencies,
        name="problems-inconsistencies",
    ),
    # path(
    #     "spectra/submit/",
    #     (
    #         login_required(
    #             views.SpectrumCreateView.as_view(),
    #             message="You must be logged in to submit a new spectrum",
    #         )
    #         if CONTRIBS_OPEN
    #         else disabled
    #     ),
    #     name="submit-spectra",
    # ),
    # path("spectra/submitted/", views.spectrum_submitted, name="spectrum_submitted"),
    # re_path(
    #     r"^spectra/submit/(?P<slug>[-\w]+)/$",
    #     (
    #         login_required(
    #             views.SpectrumCreateView.as_view(),
    #             message="You must be logged in to submit a new spectrum",
    #         )
    #         if CONTRIBS_OPEN
    #         else disabled
    #     ),
    #     name="submit-spectra",
    # ),
    # re_path(r"^spectra/(?P<slug>[-\w]+)", views.protein_spectra, name="spectra"),
    # path("spectra/", views.protein_spectra, name="spectra"),
    # path("spectra-graph/", views.protein_spectra_graph, name="spectra_graph"),
    # re_path(r"^spectra_csv/", views.spectra_csv, name="spectra_csv"),
    # re_path(
    #     r"^spectra_img/(?P<slug>[-\w]+)(\.(?P<extension>(png)|(svg)|(tif?f)|(pdf)|(jpe?g))?)?$",
    #     views.spectra_image,
    #     name="spectra-img",
    # ),
    # path(
    #     "spectra_url_builder/",
    #     TemplateView.as_view(template_name="spectrum_url_form.html"),
    #     name="spectra-url-builder",
    # ),
    # re_path(r"^fret/", views.fret_chart, name="fret"),
    # path("compare/", views.ComparisonView.as_view(), name="compare"),
    # re_path(
    #     r"^compare/(?P<proteins>[\w,\-]+)/$",
    #     views.ComparisonView.as_view(),
    #     name="compare",
    # ),
    # re_path(
    #     r"^lineage/",
    #     TemplateView.as_view(template_name="lineage.html"),
    #     name="lineage-list",
    # ),
    re_path(r"^chart/", TemplateView.as_view(template_name="ichart.html"), name="ichart"),
    re_path(
        r"^collections/(?P<owner>[\w.@+-]+)/?$",
        views.CollectionList.as_view(),
        name="collections",
    ),
    re_path(r"^collections/", views.CollectionList.as_view(), name="collections"),
    path(
        "collection/<int:pk>/",
        views.CollectionDetail.as_view(),
        name="collection-detail",
    ),
    re_path(
        r"^collection/(?P<pk>\d+)/update/",
        login_required(
            views.CollectionUpdateView.as_view(),
            message="You must be logged in to update collections",
        ),
        name="updatecollection",
    ),
    re_path(
        r"^collection/(?P<pk>\d+)/delete/",
        login_required(
            views.CollectionDeleteView.as_view(),
            message="You must be logged in to delete collections",
        ),
        name="deletecollection",
    ),
    re_path(
        r"^collection/create/",
        login_required(
            views.CollectionCreateView.as_view(),
            message="You must be logged in to create a new collection",
        ),
        name="newcollection",
    ),
    # path("activity", views.ActivityView.as_view(), name="activity"),
    # re_path(
    #     r"^protein/(?P<slug>[-\w]+)/$",
    #     views.ProteinDetailView.as_view(),
    #     name="protein-detail",
    # ),
    # path("organisms/", views.OrganismListView.as_view(), name="organism-list"),
    path(
        "organismTable/<int:pk>/",
        views.OrganismDetailView.as_view(),
        name="organismTable-detail",
    ),
    re_path(
       r"^proteinTable/(?P<slug>[-\w]+)/$", # slug is SlugField with name of gene
       # {'my_id': '?P<my_id>'}
       views.ProteinDetailView2.as_view(),
       name="proteinTable-detail",
    ),
    re_path(
       r"^repeatTable/(?P<slug>[-\w]+)/$", # slug is SlugField with name of repeat
       # {'my_id': '?P<my_id>'}
       views.RepeatDetailView.as_view(),
       name="repeatTable-detail",
    ),
    # re_path(
    #     r"^protein/(?P<slug>[-\w]+)/bleach/$",
    #     views.protein_bleach_formsets,
    #     name="protein-bleach-form",
    # ),
    re_path(
        r"^protein/(?P<slug>[-\w]+)/history/$",
        views.protein_history,
        name="protein-history",
    ),
    # re_path(
    #     r"^bleach_comparison/(?P<pk>[-\w]+)/$",
    #     views.bleach_comparison,
    #     name="bleach-comparison",
    # ),
    # path("bleach_comparison/", views.bleach_comparison, name="bleach-comparison"),
    # re_path(
    #     r"^protein/(?P<slug>[-\w]+)/rev/(?P<rev>\d+)$",
    #     views.ProteinDetailView.as_view(),
    #     name="protein-detail",
    # ),
    # re_path(
    #     r"^protein/(?P<slug>[-\w]+)/ver/(?P<ver>\d+)$",
    #     views.ProteinDetailView.as_view(),
    #     name="protein-detail",
    # ),
    path(
        "autocomplete-protein/",
        views.ProteinAutocomplete.as_view(),
        name="protein-autocomplete",
    ),
    path(
        "autocomplete-repeat/",
        views.RepeatAutocomplete.as_view(),
        name="repeat-autocomplete",
    ),
    # path(
    #     "autocomplete-lineage/",
    #     views.LineageAutocomplete.as_view(),
    #     name="lineage-autocomplete",
    # ),
    # path(
    #     "autocomplete-state/",
    #     views.StateAutocomplete.as_view(),
    #     name="state-autocomplete",
    # ),
    # path(
    #     "autocomplete-filter/",
    #     views.FilterAutocomplete.as_view(),
    #     name="filter-autocomplete",
    # ),
    # AJAX
    path("ajax/add_taxonomy/", views.add_organism, name="add_taxonomy"),
    # re_path(
    #     r"^ajax/filter_import/(?P<brand>[-\w]+)$",
    #     views.filter_import,
    #     name="filter_import",
    # ),
    re_path(
        r"^ajax/add_protein_reference/(?P<slug>[-\w]+)/$",
        views.add_reference,
        name="add_protein_reference",
    ),
    re_path(
        r"^ajax/add_protein_excerpt/(?P<slug>[-\w]+)/$",
        views.add_protein_excerpt,
        name="add_protein_excerpt",
    ),
    re_path(
        r"^ajax/admin_approve_protein/(?P<slug>[-\w]+)/$",
        views.approve_protein,
        name="admin_approve_protein",
    ),
    path(
        "ajax/admin_revert_version/<int:ver>",
        views.revert_version,
        name="admin_revert_version",
    ),
    path(
        "ajax/admin_revert_revision/<int:rev>",
        views.revert_revision,
        name="admin_revert_revision",
    ),
    # re_path(
    #     r"^ajax/update_transitions/(?P<slug>[-\w]+)/$",
    #     views.update_transitions,
    #     name="update_transitions",
    # ),
    path(
        "ajax/validate_proteinname/",
        views.validate_proteinname,
        name="validate_proteinname",
    ),
    # path(
    #     "ajax/validate_spectrumownername/",
    #     views.similar_spectrum_owners,
    #     name="validate_spectrumownername",
    # ),
    path(
        "ajax/remove_from_collection/",
        views.collection_remove,
        name="collection-remove",
    ),
    path("ajax/flag_object/", views.flag_object, name="flag_object"),
    path("ajax/add_to_collection/", views.add_to_collection, name="add_to_collection"),
    path("ajax/comparison/", views.update_comparison, name="update-comparison"),
    # re_path(r"^ajax/lineage/(?P<slug>[-\w]+)/$", views.get_lineage, name="get-lineage"),
    # path("ajax/lineage/", views.get_lineage, name="get-lineage"),
    # re_path(
    #     r"^ajax/org_lineage/(?P<org>[-\w]+)/$",
    #     views.get_lineage,
    #     name="get-org-lineage",
    # ),
    # re_path(
    #     r"^microscope/(?P<pk>[-\w]+)/report/json/$",
    #     views.scope_report_json,
    #     name="scope_report_json",
    # ),
    # re_path(r"^widget/(?P<slug>[-\w]+)/$", views.Widget.as_view(), name="widget-detail"),
]

backend/proteins/models/collection.py
from django.contrib.auth import get_user_model
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.urls import reverse
from model_utils.models import TimeStampedModel

User = get_user_model()


class OwnedCollection(TimeStampedModel):
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=512, blank=True)
    owner = models.ForeignKey(
        User,
        blank=True,
        null=True,
        related_name="%(class)s" + "s",
        on_delete=models.SET_NULL,
    )
    managers = ArrayField(models.EmailField(), default=list, blank=True)

    def has_change_permission(self, request, obj=None):
        allowed = self.managers
        if self.owner:
            allowed += [self.owner.email]
        allowed += list(User.objects.filter(is_superuser=True).values_list("email", flat=True))
        try:
            return request.user.email in allowed
        except Exception:
            return False

    def __str__(self):
        return self.name

    class Meta:
        abstract = True


class ProteinCollection(OwnedCollection):
    proteins = models.ManyToManyField("ProteinTF", related_name="collection_memberships")
    private = models.BooleanField(
        default=False,
        verbose_name="Private Collection",
        help_text="Private collections can not be seen by or shared with other users",
    )

    def get_absolute_url(self):
        return reverse("proteins:collection-detail", args=[self.id])

    class Meta:
        unique_together = ("owner", "name"),
        app_label = 'proteins'


# class FluorophoreCollection(ProteinCollection):
#     dyes = models.ManyToManyField("Dye", blank=True, related_name="collection_memberships")

#     def get_absolute_url(self):
#         return reverse("proteins:fluor-collection-detail", args=[self.id])

backend/proteins/models/repeat.py
import os

from django.conf import settings
from django.contrib.postgres.fields import ArrayField
from django.db import models
from django.urls import reverse
import requests

from backend.fpseq.util import slugify
from ..util.helpers import shortuuid
import json

class Repeat(models.Model):
    id = models.CharField(primary_key=True, max_length=22, default=shortuuid, editable=False)
    name = models.CharField(max_length=200, blank=True, null=True, unique=True)
    slug = models.SlugField(max_length=200, blank=True, null=True)
    aliases = ArrayField(
        models.TextField(blank=True, null=True),
        blank=True,
        null = True
    )
    motif = models.TextField(blank=True, null=True)
    dfam_id = models.CharField(max_length=100, blank=True, null=True)
    parent_repeat = models.ForeignKey(
        "self", 
        related_name='children',
        verbose_name='parental repeat',
        on_delete=models.SET_NULL,
        blank=True,
        null=True
    )
    parental_organism = models.ForeignKey(
        "Organism",
        # related_name="organism",
        verbose_name="Parental organism",
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        help_text="Organism from which the protein was engineered",
    )
    # references = models.ForeignKey(
    #     "Reference",
    #     related_name="reference",
    #     verbose_name="Reference",
    #     on_delete=models.SET_NULL,
    #     blank=True,
    #     null=True,
    #     help_text="References for repeats",
    # ),
    references = models.TextField(blank=True, null=True)

    def get_absolute_url(self):
        return reverse("proteins:repeatTable-detail", args=[self.slug])
    
    def aliases_as_str(self):
        # print(self.aliases)
        if self.aliases:
            return ", ".join(self.aliases)
        else:
            return "None"

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)
        
    def get_proteins(self):
        return self.proteintf_set.all()
    
    def get_protein_lst(self):
        return list(self.proteintf_set.all())


    # def get_HMM(self):
    #     with pyhmmer.plan7.HMMFile("data/hmms/txt/PKSI-AT.hmm") as hmm_file:
    #         hmm = hmm_file.read()
    
    def get_hmm(self):
        if self.dfam_id:
            hmm_url = f"https://dfam.org/api/families/{self.dfam_id}/hmm?format=logo"
            r = requests.get(hmm_url)
            if r.status_code != 200:
                raise Exception(f"HMM not found for {self.dfam_id}")

            return r.text
        return None
    
    def karyoplot_exists(self):
        name_lower = self.repeat_lower()
        file_path = f"{settings.ROOT_DIR.parent}/frontend/static/karyoplot/human_{name_lower}_blocks.svg"  # Replace with your actual path
        if os.path.exists(file_path):
            # File or directory exists
            return True
        else:
            return False
        
    def repeat_lower(self):
        return self.name.lower()

        
        

backend/proteins/views/blast.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import ensure_csrf_cookie

from repeatome.util import is_ajax

from ..util.blast import blast


@ensure_csrf_cookie
def blast_view(request):
    if not is_ajax(request):
        return render(request, "proteins/blast.html")

    seq = request.POST.get("query")
    binary = request.POST.get("binary", "blastp")
    assert binary in ("blastx", "blastp")
    if seq:
        try:
            result = blast(seq, binary)
            return JsonResponse({"status": 200, "blastResult": result})
        except Exception as e:
            return JsonResponse({"status": 500, "error": f"BLAST error: {e}"})
    return JsonResponse({"status": 204, "blastResult": []})

backend/proteins/views/karyotype.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views.decorators.csrf import ensure_csrf_cookie

from repeatome.util import is_ajax

from ..util.blast import blast


def karyotype_view(request):
    return render(request, "proteins/karyotype_viewer.html")

backend/proteins/views/mixins.py
class OwnableObject:
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def attach_owner(self, form):
        self.object = form.save(commit=False)
        if not self.object.owner:
            self.object.owner = self.request.user
        self.object.save()

backend/proteins/templates/proteins/_loading_logo.html
  <div style="position: relative; width: 82%; margin: auto; margin-top: 6%;">
      <svg xmlns="http://www.w3.org/2000/svg" height="40%" viewBox="0 0 2947 1061"
          style="fill-rule: evenodd; width: 100%">
          <style>
              text {
                  font: 30px sans-serif;
                  font-weight: 600;
                  font-size: 11rem;
              }
          </style>
          <defs>
              <linearGradient id="lightGradient">
                  <stop offset="0%" stop-color="#666">
                  </stop>
                  <stop offset="100%" stop-color="#eee">
                  </stop>
              </linearGradient>
          </defs>
          <path fill="url(#lightGradient)"
              d="M2947,1060.88s-624.57-60.18-1103.06-405.741C1525.93,409.081,1419.45-13.191,1341.92.314c-95.24,10.978-78.62,259.289-202.86,656.871-130.38,402.445-420.5,403.7-420.5,403.7H2947Zm-1445.59,0s-201.41-.43-287.43-335.216C1110.65,323.49,1096.05,1,1047.32,1.221,977.2,1.535,902.926,557.3,647.811,769.037,308.211,1050.89,0,1060.88,0,1060.88H1501.41Z"></path>
          <text x="900" y="570" class="bold" fill="#ccc">loading...</text>
      </svg>
  </div>

backend/proteins/templates/proteins/collection_remove_button.html
{% load i18n %}
<a class="btn btn-sm collection-remove" href='' data-action-url="{% url 'proteins:collection-remove' %}" data-object="{{ target_protein }}" data-collection="{{ target_collection }}">
  <i class="fas fa-times-circle text-danger"></i>
</a>

backend/proteins/templates/proteins/karyotype_viewer.html
{% extends "base.html" %}
{% load static i18n favit_tags %}
{% load static %}
{% load render_bundle from webpack_loader %}

{% block title %}Karyotype Viewer {% endblock %}
{% block meta-description %}Karyotype Viewer{% endblock %}


{% block content %}

  <h1 class="name text-center mb-4">Karyotype Viewer</h1>

  <h5 class='pt-3'><strong>Karyotype Viewer</strong></h5>
  <div id='karyotype_div'></div>

  {% render_bundle 'karyotypeViewer' %}

{% endblock content %}

backend/proteins/templates/proteins/microscope_confirm_delete.html
{% extends "base.html" %}

{% block title %}Delete {{ object }}?{% endblock %}

{% block content %}

<form action="" method="post">{% csrf_token %}
  <div class="clearfix">
    <h1 class='mb-4'>Delete Microscope?</h1>
    <div class="float-left mr-3 ml-2" style="font-size:2.8rem; height:100px; position: relative; top: -10px; margin-bottom: -10px"><p class="mb-0 pb-0">🔬</p><p style="position:relative; top: -3.2rem; left: -4px; font-size:3.3rem;">🕳</p></div>
    <p><strong>Are you sure you want to delete the microscope "{{ object }}"</strong>?<br>(This cannot be undone.)</p>
  </div>

  <input class='btn btn-danger' type="submit" value="Delete {{ object }}" title="Delete" />
</form>
<a href="{% url 'proteins:updatemicroscope' object.id %}"><button class='btn btn-info btn-sm mt-2'>Edit configurations instead</button></a>
</form>
<a href="{% url 'proteins:microscope-detail' object.id %}"><button class='btn btn-info btn-sm mt-2'>Go to microscope page</button></a>

{% endblock content %}

backend/proteins/templates/proteins/protein_bleach_form.html
{% extends "base.html" %}

{% load crispy_forms_tags static %}

{% block content %}
<h2>Update {{protein.name}} Bleach Measurements</h2>

<p>Note: If you are entering a bleach measurement from a reference that compared multiple proteins in a single experiment, it is easier to use the form from that specific reference page instead.  Click on the title of a reference towards the bottom of any protein page, or search for the reference in the <a href="{% url 'reference-list' %}">references table</a></p>
<form id="bleachform" action="" method="post">
	{% csrf_token %}
	<input type="hidden" name="slug" id="id_slug" value='{{ protein.slug }}'>

	{{ formset.management_form|crispy }}
	{% for form in formset %}
	    {% for hidden in form.hidden_fields %}
	        {{ hidden }}
	    {% endfor %}
		<div class="row formset_div">
			<div class='col bleach-col'>
				{% if form.instance.pk %}{{ form.DELETE }}{% endif %}
				{% crispy form form.helper %}
			</div>
	    </div>
	{% endfor %}  <!-- end formset loop  -->


	<input type="submit" class='btn btn-primary mb-4' value="Submit" />
	<a href="{{ protein.get_absolute_url }}"><input type="button" class='btn btn-danger mb-4' value="Cancel" /></a>

</form>

{% endblock content %}


{% block javascript %}

	<script type="text/javascript">
	$(function () {

		var deleteclass = 'bleach-delete-button'

		$('.formset_div').formset({
			addText: 'Add Bleach Measurement',
			addCssClass: 'btn btn-info mb-4',
			deleteCssClass: deleteclass + '',
			deleteText: '&times;',
			processHidden: true,
			prefix: 'form',
		});

		// if this is an update view without post data, remove the last (empty) state
		{% if protein and formset.management_form.initial.TOTAL_FORMS > 1 %}
			{% if not request.POST %}
			$('.dynamic-form').last().find('.' + deleteclass).click()
			{% endif %}
		{% endif %}

	});

	</script>

{% endblock javascript%}

backend/proteins/templates/proteins/protein_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags static %}
{% load static %}

{% block title %}{% if object %}Update {{ object.name }}{% else %}Submit a protein to FPbase{% endif %}{% endblock %}

{% block meta-description %}{% if object %}This page allows users with an account at FPbase to update information relating to the protein {{ object.name}}{% else %}This page allows users with an account at FPbase to add a new protein to the database{% endif %}{% endblock %}

{% block extrahead %}
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>
{% endblock extrahead %}

{% block content %}

  <div>
    {% if object %} {% comment %} object means this is an update form {% endcomment %}
        <h1>Update {{ object.name }}</h1>
    {% else %}
        <h1>Submit a new protein</h1>
    {% endif %}

	<div class="small alert alert-info fade show mt-4" role="alert">
		<div class='h5 text-info'><i class="fas fa-eye mr-2 "></i> <strong>Thank you for contributing to FPbase!</strong></div>
		<p>You are about to suggest changes for the <em>public</em> database (not your private collection).</p>

		{% if not object %}
		<p>The only strictly required fields are name and DOI.  You may enter some fields now, and update with additional info later.</p>
		{% endif %}

		<p><strong>Once submitted, data cannot be edited or deleted without contacting FPbase.  Please double check your submission for accuracy</strong></p>
		<p>If you think there is an error or wish to make a correction, please <a href="{% url 'contact' %}">contact us</a></p>
	</div>

	{% if states.non_form_errors %}
		<h5>There were errors in the form...</h5>
		<div class="alert alert-danger" role="alert">
		  {{ states.non_form_errors }}
		</div>
	{% endif %}

	<div>
	    <form id="proteinform" action="" method="post" data-validate-proteinname-url="{% url 'proteins:validate_proteinname' %}">
	    	{% csrf_token %}
	    	<input type="hidden" name="slug" id="id_slug" value='{% if protein.slug %}{{ protein.slug }}{% endif %}'>
	        <div class='row'>
	        	<div class='col'>
	        		{% crispy form %}
				    </div>
			    </div>

        {% if lineage.non_form_errors %}
          <div class="alert alert-danger" role="alert">
            {{ lineage.non_form_errors }}
          </div>
        {% endif %}
        {{ lineage.management_form|crispy }}
        {% for lineageform in lineage.forms %}
          {% for hidden in lineageform.hidden_fields %}
                {{ hidden }}
            {% endfor %}
      <div class="row">
        <div class='col lineage-col'>
          {% crispy lineageform lineageform.helper %}
        </div>
          </div>
        {% endfor %}  <!-- end formset loop  -->

			<div class="small alert alert-info alert-dismissible fade show mt-4" role="alert">
			  <div class='h5 text-info'><i class="fas fa-info-circle mr-2 "></i> <strong>States</strong></div>
			  FPbase uses <strong>states</strong> to encapsulate the various fluorescence characteristics that a protein can have.  Even a constitutively active "basic" protein is given a (single) state.  Rather than directly specifying the "type" of protein, FPbase uses the number of states and transitions between them to determine the type of fluorescent protein.<br><br>

			  For <span style='color: green'>photo</span><span style='color: red'>chromic</span> proteins, first declare all states on this form (including dark states), then add state transitions on the main protein page.<br>More info available on the <a href="{% url 'schema' %}" class="alert-link">database model</a> info page.
			  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
			      <span aria-hidden="true">&times;</span>
			    </button>
			</div>

	        {{ states.management_form|crispy }}
	        {% for stateform in states.forms %}
		        {% for hidden in stateform.hidden_fields %}
	                {{ hidden }}
	            {% endfor %}
				<div class="row formset_div">
					<div class='col state-col'>
						{% if stateform.instance.pk %}{{ stateform.DELETE }}{% endif %}
						{% crispy stateform stateform.helper %}
					</div>
		        </div>
	        {% endfor %}  <!-- end formset loop  -->

	        {% if object %}
	            <input type="submit" class='btn btn-primary mb-4' value="Submit" />
	            <a href="{{ protein.get_absolute_url }}"><input type="button" class='btn btn-danger mb-4' value="Cancel" /></a>
	        {% else %}
	            <input type="submit" class='btn btn-primary mb-4' value="Save Protein"/>
	        {% endif %}
	        <p style='color: gray; font-size: 0.8rem;' class='hidden transition-note'><em><i class='fas fa-exchange-alt mr-2'></i>For <span style='color: green'>photo</span><span style='color: red'>chromic</span> proteins, first declare all states on this form (including dark states), then add state transitions on the main protein page.</em></p>
	    </form>
	</div>

{% include 'proteins/modals/_organism_modal.html'  %}

{% endblock %}


{% block javascript %}

	<script type="text/javascript">

		$(function () {

			var deleteclass = 'state-delete-button'

			$('.formset_div').formset({
				addText: 'Add State',
				addCssClass: 'btn btn-info mb-4',
				deleteCssClass: deleteclass,
				deleteText: '&times;',
				processHidden: true,
				prefix: 'states' 	 // it's important that this match the string used for the
									 // related_name attribute in the "protein" foreign key field
									 // in the State model

			});

			if ($("#id_ipg_id").val()){
				//$("#id_seq").prop('disabled', true);
				//$("#hint_id_seq").html('Sequence input disabled when IPG ID provided');
			}

			// if this is an update view without post data, remove the last (empty) state
			{% if object %}
				{% if not request.POST %}
				$('.dynamic-form').last().find('.' + deleteclass).click()
				{% endif %}
			{% endif %}


			$('#id_states-TOTAL_FORMS').change(function(){
				if (this.value > 1){
					$('.transition-note').show()
				} else {
					$('.transition-note').hide()
				}
			});

			$("form").submit(function (e) {
			   if ($("#id_name").hasClass('is-invalid')) {
			      e.preventDefault();
			      $("html, body").animate({ scrollTop: 0 }, "slow");
			      return false;
			   }
			});

		})

	</script>

{% endblock javascript%}